[Unit]
Requires=dsh-control-plane-netns.service
After=dsh-control-plane-netns.service
JoinsNamespaceOf=dsh-control-plane-netns.service

[Service]
PrivateNetwork=true
RuntimeDirectory=dsh-control-plane
RuntimeDirectoryMode=0750
UMask=0007